#+title: AutoPi

*AutoPi* is a driving assistance project that helps in you drive safely.
This project aims to provide an ultimate safety companion for your ride using an embedded system that combines drowsiness detection, alcohol detection, and Lidar technology to keep you and others safe on the road. The system detects whether the driver is intoxicated or sleepy and sends an alert to their loved ones for their protection.

The project utilizes smart technology to enhance road safety and prevent accidents caused by drunk or drowsy driving. The code for this project is available on GitHub, and we encourage developers to contribute and make the roads safer for everyone.

* Contributors



* Build Instructions
#+begin_quote
Install meson and ninja for building
#+end_quote

#+begin_src bash
meson setup build
cd build
# to complile project run
meson compile
# to run tests run
meson test
#+end_src


* Follow us on
#+begin_quote
[[https://www.instagram.com/aut_opi/][https://img.icons8.com/officel/40/000000/instagram-new.png]][AutoPi]



#+end_quote

